### ISSUE TITLE
lookupInvoice() no longer working in my implementation

### ISSUE THREAD

**Issue by PierreCorbin** [getAlby/js-sdk#173]
After the most recent changes to the code (from what I gather, for nip-47), my implementation of lookupInvoice() stopped working. I went through the commit and can't identify the problem.

Here is my code to lookup the invoice:

```
// Create NWC instance
const NWC = new webln.NostrWebLNProvider({
    nostrWalletConnectUrl: nostrWalletConnectUrl,
});
// Connect to NWC
await NWC.enable();
// Lookup Invoice
const invoiceDetails = await NWC.lookupInvoice({ paymentRequest: invoice });
```

In the code above, invoice is the result of the following code (a string like "lnbc1u1pjc0akepp5cgrzdus4hzv77nrk..."):
```
// Create NWC instance
const NWC = new webln.NostrWebLNProvider({
    nostrWalletConnectUrl: nostrWalletConnectUrl,
});
// Connect to NWC
await NWC.enable();
// Create invoice
const invoice = await NWC.makeInvoice({ amount, defaultMemo: memo });
// Return the result
res.json({ invoice: invoice.paymentRequest });
```

Please help! Thanks!

**Comment by bumi** [comment]
Hey, I assume this is with an Alby account?

**Comment by PierreCorbin** [comment]
That's right

**Comment by bumi** [comment]
And you don't get a return value from `lookupInvoice` ?

**Comment by PierreCorbin** [comment]
that's right, I get this error:
Error object: {
error: 'Failed to decode bolt11 invoice: bolt11 too short',
code: 'INTERNAL'
}

All the code before that, my NWCs, etc, are all correct.

**Comment by bumi** [comment]
oh, ok. thanks. can you send me an example invoice that you get (DM if you want)

**Comment by bumi** [comment]
can you try:
```
const invoiceDetails = await NWC.lookupInvoice({ invoice: invoice });
```

this might have changed (https://github.com/nostr-protocol/nips/pull/685/files#diff-d1ed4c38da272aa7f99e29edb6739e8fb209c723585601a84f0fd511d1c679e0R238) 

but that spec is now implemented and should be fixed.

**Comment by PierreCorbin** [comment]
The response looks better, but still with an error:

```
Error object: {
  error: 'Response from NWC failed validation: {"type":"incoming","invoice":"lnbc1u1pjcsp4zpp5wx88w3ua...","description":"","description_hash":"","preimage":"","payment_hash":"718e77479...","amount":100000,"fees_paid":0,"created_at":"2023-12-24T10:23:30.41Z","expires_at":"2023-12-25T10:23:30Z","settled_at":null}',
  code: 'INTERNAL'
}
```

**Comment by bumi** [comment]
what version do you use? 

there seems to be actually some inconsistency: https://github.com/getAlby/js-sdk/blob/471087190f5e0909c87c0e12cb69926248b89fb7/src/webln/NostrWeblnProvider.ts#L400-L404

investigating

**Comment by bumi** [comment]
So I was wrong. here in the SDK the lookupInvoice call still takes the `paymentRequest`

```
await NWC.lookupInvoice({ paymentRequest: invoice });
```
this works for me on the latest master.

**Comment by PierreCorbin** [comment]
Ok, thanks. I may be having some versioning problems on my server. I'll spend some more time on this after Christmas. Thanks for the help and Merry Christmas!

**Comment by rolznz** [comment]
@PierreCorbin if you have any troubles please let us know. Unfortunately there was a breaking change because the NIP-47 spec is not finalized yet. Updating to the latest version of JS-SDK should fix your issue.

**Comment by PierreCorbin** [comment]
Thanks, I got it to work. The issue I was running into was that running:
`npm install @getalby/sdk
`
Was only installing v 2.7.0. I had to run:
`npm install @getalby/sdk@3.3.2
`
