### ISSUE TITLE
Add token changed callback

### ISSUE THREAD

**Issue by rolznz** [getAlby/js-sdk#31]
Currently it is difficult to figure out when the refresh/access token pair changes (since it happens internally on request), which needs to be stored by the client app.

I found https://github.com/googleapis/google-api-nodejs-client seems to manage refreshing the token automatically for the client and exposes an .on('tokens') callback so apps can subscribe to token changes and store the credentials themselves (for next time the app is initialized).

Can we do the same here and update the documentation in the README so it is obvious how to manage tokens?
- Tokens are updated automatically
- Use this method to subscribe to changes and store the token yourself

**Comment by bumi** [comment]
good idea, this then should also should be used by the webln provider and exposed there https://github.com/getAlby/alby-js-sdk/blob/master/src/webln/OauthWeblnProvider.ts#L29-L38
