### ISSUE TITLE
user_agent is only passed in token requests

### ISSUE THREAD

**Issue by rolznz** [getAlby/js-sdk#52]
other requests for some reason seem to use alby-js-api instead.

**Comment by pavanjoshi914** [comment]
what's the issue here really? i didn't get

**Comment by pavanjoshi914** [comment]
@rolznz  this is resolved isn't it ?

**Comment by rolznz** [comment]
@pavanjoshi914 the issue should probably be fixed in this library rather than having to pass the options to every request like you did in https://github.com/getAlby/lightning-browser-extension/pull/2837/files 

Can you please test this and see how we can cleanly do it?

We need to make sure the user agent that is used **(and all other properties)** is the one the user gave when initializing the client.

**Comment by pavanjoshi914** [comment]
closing this as fixed in the extension itself
